# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/tattoo/extract-files.sh

# libgps is necessary to complete the compilation
PRODUCT_COPY_FILES += \
    device/htc/tattoo/custom/logo.rle:root/logo.rle \
    device/htc/tattoo/proprietary/libgps.so:obj/lib/libgps.so \
    device/htc/tattoo/proprietary/fakecam/libcamera.so:obj/lib/libcamera.so

# Proprietary stuff
PRODUCT_COPY_FILES += \
    device/htc/tattoo/proprietary/akm8973:system/bin/akm8973 \
    device/htc/tattoo/proprietary/AudioPara4.csv:system/etc/AudioPara4.csv \
    device/htc/tattoo/proprietary/AudioFilter.csv:system/etc/AudioFilter.csv \
    device/htc/tattoo/proprietary/AudioPreProcess.csv:system/etc/AudioPreProcess.csv \
    device/htc/tattoo/proprietary/fakecam/liboemcamera.so:system/lib/liboemcamera.so \
    device/htc/tattoo/proprietary/fakecam/libcamera.so:system/lib/libcamera.so \
    device/htc/tattoo/proprietary/libGLES_qcom.so:system/lib/egl/libGLES_qcom.so \
    device/htc/tattoo/proprietary/libgps.so:system/lib/libgps.so \
    device/htc/tattoo/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    device/htc/tattoo/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    device/htc/tattoo/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    device/htc/tattoo/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    device/htc/tattoo/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    device/htc/tattoo/proprietary/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    device/htc/tattoo/proprietary/libhtc_ril.so:system/lib/libhtc_ril.so
